server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: pictora-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pictora
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
# MyBatis - Plus配置
mybatis-plus:
  configuration:
    # 自动转换为驼峰格式
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名
      logic-delete-value: 1         # 逻辑已删除值
      logic-not-delete-value: 0     # 逻辑未删除值

# 接口文档
knife4j:
  enable: true
  openapi:
    title: 云图阁项目接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yufei.pictorabackend.controller